﻿common:
  ip: 127.0.0.1
server:
  port: 9998
spring:
  datasource:
    druid:
      url: jdbc:mysql://${common.ip}:3306/facedb?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false
      username: root
      password: CJ8AzTiVwZdJihNuyeYOeNpzeo1KndhRRlGr2wH5crWe9s4sYFbtGi5iUzva5l4YfBRqhz4zyGYv4miC8rjVww==
      #连接池的配置信息
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: false
      test-on-borrow: false
      test-on-return: false
      filter.config.enabled: true
      filters: stat,wall
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALBCiB/HyM/WdejJ+3ZPHLATs+/2QyLxBi+3Qx/ftXmYb3O4U3MyVMkmXjYbd8MKYj7WwXXCVzv0j8qxj7ejvSsCAwEAAQ==
      use-global-data-source-stat: true
  aop:
    auto: true
#pagehelper分页插件配置
pagehelper:
  #查询合理化,如果页数过大,默认查询最后一页
  reasonable: false
  #分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页(禁止使用)
  support-methods-arguments: false
  #用于从对象中根据属性名取值
  params: count=countSql
  #数据库类型,可以不配置,插件默认检测
  helper-dialect: mysql

# 下划线到驼峰形式的映射
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ferret.bean
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true


#上传文件/图片的保存路径,替换url路径
image:
  prefix:
    # 1.上传图片地址的路径目录前缀
    uploadDir: E:/ftpdata/upload
    # 替换成url路径的地址前缀
    uploadUrl: http://${common.ip}:${server.port}/upload